<?php declare(strict_types=1);

namespace Loevgaard\DandomainConsignment\Entity;

use Assert\Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model\Timestampable\Timestampable;
use Loevgaard\DandomainConsignment\Entity\Generated\ReportInterface;
use Loevgaard\DandomainConsignment\Entity\Generated\ReportTrait;
use Loevgaard\DandomainFoundation\Entity\Generated\ManufacturerInterface;
use Loevgaard\DandomainStock\Entity\Generated\StockMovementInterface;
use Money\Currency;
use Money\Money;
use Symfony\Component\Validator\Constraints as FormAssert;

/**
 * @ORM\Entity()
 * @ORM\Table(name="ldc_reports")
 * @ORM\HasLifecycleCallbacks()
 */
class Report implements ReportInterface
{
    use ReportTrait;
    use Timestampable;

    const STATUS_ERROR = 'error';
    const STATUS_PENDING = 'pending';
    const STATUS_SUCCESSFUL = 'successful';

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @ORM\Id
     */
    protected $id;

    /**
     * @var ManufacturerInterface
     *
     * @FormAssert\NotBlank()
     *
     * @ORM\ManyToOne(targetEntity="Loevgaard\DandomainFoundation\Entity\Manufacturer")
     * @ORM\JoinColumn(onDelete="CASCADE", nullable=false)
     */
    protected $manufacturer;

    /**
     * @var string
     *
     * @FormAssert\Choice(callback="getStatuses")
     *
     * @ORM\Column(type="string", length=191)
     */
    protected $status;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $error;

    /**
     * Is true if this report can be 'safely' deleted
     * In practice this means that it was not generated by a cron task, and/or not sent to a supplier
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $deletable;

    /**
     * @var StockMovementInterface[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Loevgaard\DandomainStock\Entity\StockMovement")
     * @ORM\JoinTable(name="ldc_reports_stock_movements")
     * @ORM\OrderBy({"createdAt" = "ASC"})
     */
    protected $stockMovements;

    public function __construct()
    {
        $this->status = self::STATUS_PENDING;
        $this->deletable = false;
        $this->stockMovements = new ArrayCollection();
    }

    public function markAsError(?string $error = null)
    {
        $this->status = self::STATUS_ERROR;
        $this->error = $error;
    }

    public function markAsSuccess()
    {
        $this->status = self::STATUS_SUCCESSFUL;
        $this->error = null;
    }

    public function isStatus(string $status) : bool
    {
        return $this->status === $status;
    }

    public function isSuccessful() : bool
    {
        return $this->isStatus(self::STATUS_SUCCESSFUL);
    }

    public function isError() : bool
    {
        return $this->isStatus(self::STATUS_ERROR);
    }

    /**
     * Returns true if the report can be delivered to the consignor
     *
     * @return bool
     */
    public function isDeliverable() : bool
    {
        return $this->isSuccessful();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function validate()
    {
        Assert::that($this->manufacturer)->isInstanceOf(ManufacturerInterface::class);
        Assert::that($this->status)->string()->choice(self::getStatuses());
    }

    public static function getStatuses() : array
    {
        return [
            self::STATUS_PENDING => self::STATUS_PENDING,
            self::STATUS_SUCCESSFUL => self::STATUS_SUCCESSFUL,
            self::STATUS_ERROR => self::STATUS_ERROR
        ];
    }

    public function addStockMovement(StockMovementInterface $stockMovement) : ReportInterface
    {
        if (!$this->stockMovements->contains($stockMovement)) {
            $this->stockMovements->add($stockMovement);
        }

        return $this;
    }

    public function removeStockMovement(StockMovementInterface $stockMovement) : ReportInterface
    {
        $this->stockMovements->removeElement($stockMovement);

        return $this;
    }

    public function clearStockMovements() : ReportInterface
    {
        foreach ($this->stockMovements as $stockMovement) {
            $this->removeStockMovement($stockMovement);
        }

        return $this;
    }

    /**
     * Will return the total for all stock movements
     *
     * @return Money
     */
    public function getTotal() : Money
    {
        $total = null;

        foreach ($this->stockMovements as $stockMovement) {
            if(!$total) {
                $total = new Money(0, $stockMovement->getTotalPrice()->getCurrency());
            }

            $total = $total->add($stockMovement->getTotalPrice());
        }

        if(!$total) {
            $total = new Money(0, new Currency('DKK'));
        }

        return $total;
    }

    /*
     * Getters / Setters
     */

    /**
     * @return int
     */
    public function getId(): int
    {
        return (int)$this->id;
    }

    /**
     * @param int $id
     * @return ReportInterface
     */
    public function setId(int $id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return ManufacturerInterface
     */
    public function getManufacturer(): ManufacturerInterface
    {
        return $this->manufacturer;
    }

    /**
     * @param ManufacturerInterface $manufacturer
     * @return ReportInterface
     */
    public function setManufacturer(ManufacturerInterface $manufacturer)
    {
        $this->manufacturer = $manufacturer;
        return $this;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return ReportInterface
     */
    public function setStatus(string $status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * @param null|string $error
     * @return ReportInterface
     */
    public function setError(?string $error)
    {
        $this->error = $error;
        return $this;
    }

    /**
     * @return bool
     */
    public function isDeletable(): bool
    {
        return $this->deletable;
    }

    /**
     * @param bool $deletable
     * @return ReportInterface
     */
    public function setDeletable(bool $deletable)
    {
        $this->deletable = $deletable;
        return $this;
    }

    /**
     * @return StockMovementInterface[]|ArrayCollection
     */
    public function getStockMovements()
    {
        return $this->stockMovements;
    }

    /**
     * @param StockMovementInterface[]|ArrayCollection $stockMovements
     * @return ReportInterface
     */
    public function setStockMovements($stockMovements)
    {
        $this->stockMovements = $stockMovements;
        return $this;
    }
}
